export const teamData = [
    {
      "rank": 32,
      "team": "Arizona Cardinals",
      "abbreviation": "ARI",
      "bye": 12,
      "pointsFor": 225,
      "yards": 3865,
      "plays": 902,
      "yardsPerPlay": 4.3,
      "turnovers": 28,
      "completions": 283,
      "attempts": 495,
      "passYardsTeam": 2523,
      "passTdTeam": 15,
      "interception": 18,
      "netYardsPerAttempt": 4.6,
      "rushAttemptTeam": 355,
      "rushYardsTeam": 1342,
      "rushTdTeam": 9,
      "yardsPerRush": 3.8,
      "scorePercentage": 19.3,
      "turnoverPercentage": 15,
      "offensiveLineRank": 29,
      "runningBackSoS": 8,
      "passRank": 32,
      "rushRank": 30,
      "imageUrl": "http://content.sportslogos.net/logos/7/177/thumbs/kwth8f1cfa2sch5xhjjfaof90.gif"
    },
    {
      "rank": 10,
      "team": "Atlanta Falcons",
      "abbreviation": "ATL",
      "bye": 9,
      "pointsFor": 414,
      "yards": 6226,
      "plays": 1010,
      "yardsPerPlay": 6.2,
      "turnovers": 18,
      "completions": 428,
      "attempts": 617,
      "passYardsTeam": 4653,
      "passTdTeam": 36,
      "interception": 7,
      "netYardsPerAttempt": 7.1,
      "rushAttemptTeam": 351,
      "rushYardsTeam": 1573,
      "rushTdTeam": 11,
      "yardsPerRush": 4.5,
      "scorePercentage": 42.9,
      "turnoverPercentage": 10.7,
      "offensiveLineRank": 11.5,
      "runningBackSoS": 32,
      "passRank": 4,
      "rushRank": 24,
      "imageUrl": "http://content.sportslogos.net/logos/7/173/thumbs/299.gif"
    },
    {
      "rank": 13,
      "team": "Baltimore Ravens",
      "abbreviation": "BAL",
      "bye": 8,
      "pointsFor": 389,
      "yards": 5999,
      "plays": 1135,
      "yardsPerPlay": 5.3,
      "turnovers": 20,
      "completions": 334,
      "attempts": 556,
      "passYardsTeam": 3558,
      "passTdTeam": 18,
      "interception": 9,
      "netYardsPerAttempt": 6.1,
      "rushAttemptTeam": 547,
      "rushYardsTeam": 2441,
      "rushTdTeam": 19,
      "yardsPerRush": 4.5,
      "scorePercentage": 40.7,
      "turnoverPercentage": 10.7,
      "offensiveLineRank": 10.8,
      "runningBackSoS": 1,
      "passRank": 20,
      "rushRank": 5,
      "imageUrl": "http://content.sportslogos.net/logos/7/153/thumbs/318.gif"
    },
    {
      "rank": 30,
      "team": "Buffalo Bills",
      "abbreviation": "BUF",
      "bye": 6,
      "pointsFor": 269,
      "yards": 4778,
      "plays": 1008,
      "yardsPerPlay": 4.7,
      "turnovers": 32,
      "completions": 271,
      "attempts": 499,
      "passYardsTeam": 2794,
      "passTdTeam": 13,
      "interception": 23,
      "netYardsPerAttempt": 5.2,
      "rushAttemptTeam": 468,
      "rushYardsTeam": 1984,
      "rushTdTeam": 15,
      "yardsPerRush": 4.2,
      "scorePercentage": 26.4,
      "turnoverPercentage": 15.5,
      "offensiveLineRank": 24.3,
      "runningBackSoS": 16,
      "passRank": 31,
      "rushRank": 20,
      "imageUrl": "http://content.sportslogos.net/logos/7/149/thumbs/n0fd1z6xmhigb0eej3323ebwq.gif"
    },
    {
      "rank": 14,
      "team": "Carolina Panthers",
      "abbreviation": "CAR",
      "bye": 7,
      "pointsFor": 376,
      "yards": 5972,
      "plays": 1011,
      "yardsPerPlay": 5.9,
      "turnovers": 22,
      "completions": 378,
      "attempts": 563,
      "passYardsTeam": 3836,
      "passTdTeam": 28,
      "interception": 16,
      "netYardsPerAttempt": 6.4,
      "rushAttemptTeam": 416,
      "rushYardsTeam": 2136,
      "rushTdTeam": 17,
      "yardsPerRush": 5.1,
      "scorePercentage": 37,
      "turnoverPercentage": 12.1,
      "offensiveLineRank": 10.3,
      "runningBackSoS": 10,
      "passRank": 14,
      "rushRank": 3,
      "imageUrl": "http://content.sportslogos.net/logos/7/174/thumbs/f1wggq2k8ql88fe33jzhw641u.gif"
    },
    {
      "rank": 9,
      "team": "Chicago Bears",
      "abbreviation": "CHI",
      "bye": 6,
      "pointsFor": 421,
      "yards": 5502,
      "plays": 1013,
      "yardsPerPlay": 5.4,
      "turnovers": 24,
      "completions": 344,
      "attempts": 512,
      "passYardsTeam": 3564,
      "passTdTeam": 28,
      "interception": 14,
      "netYardsPerAttempt": 6.5,
      "rushAttemptTeam": 468,
      "rushYardsTeam": 1938,
      "rushTdTeam": 16,
      "yardsPerRush": 4.1,
      "scorePercentage": 36.8,
      "turnoverPercentage": 13.2,
      "offensiveLineRank": 11.5,
      "runningBackSoS": 9,
      "passRank": 13,
      "rushRank": 12,
      "imageUrl": "http://content.sportslogos.net/logos/7/169/thumbs/364.gif"
    },
    {
      "rank": 17,
      "team": "Cincinnati Bengals",
      "abbreviation": "CIN",
      "bye": 9,
      "pointsFor": 368,
      "yards": 4972,
      "plays": 938,
      "yardsPerPlay": 5.3,
      "turnovers": 17,
      "completions": 331,
      "attempts": 542,
      "passYardsTeam": 3290,
      "passTdTeam": 27,
      "interception": 13,
      "netYardsPerAttempt": 5.7,
      "rushAttemptTeam": 359,
      "rushYardsTeam": 1682,
      "rushTdTeam": 13,
      "yardsPerRush": 4.7,
      "scorePercentage": 35.5,
      "turnoverPercentage": 9.6,
      "offensiveLineRank": 25.5,
      "runningBackSoS": 20,
      "passRank": 18,
      "rushRank": 16,
      "imageUrl": "http://content.sportslogos.net/logos/7/154/thumbs/403.gif"
    },
    {
      "rank": 20,
      "team": "Cleveland Browns",
      "abbreviation": "CLE",
      "bye": 7,
      "pointsFor": 359,
      "yards": 5900,
      "plays": 1023,
      "yardsPerPlay": 5.8,
      "turnovers": 24,
      "completions": 353,
      "attempts": 574,
      "passYardsTeam": 4007,
      "passTdTeam": 29,
      "interception": 17,
      "netYardsPerAttempt": 6.5,
      "rushAttemptTeam": 411,
      "rushYardsTeam": 1893,
      "rushTdTeam": 15,
      "yardsPerRush": 4.6,
      "scorePercentage": 31.2,
      "turnoverPercentage": 11.4,
      "offensiveLineRank": 20.3,
      "runningBackSoS": 19,
      "passRank": 23,
      "rushRank": 19,
      "imageUrl": "http://content.sportslogos.net/logos/7/155/thumbs/15578552015.gif"
    },
    {
      "rank": 22,
      "team": "Dallas Cowboys",
      "abbreviation": "DAL",
      "bye": 8,
      "pointsFor": 339,
      "yards": 5501,
      "plays": 1022,
      "yardsPerPlay": 5.4,
      "turnovers": 17,
      "completions": 356,
      "attempts": 527,
      "passYardsTeam": 3538,
      "passTdTeam": 22,
      "interception": 8,
      "netYardsPerAttempt": 6.1,
      "rushAttemptTeam": 439,
      "rushYardsTeam": 1963,
      "rushTdTeam": 13,
      "yardsPerRush": 4.5,
      "scorePercentage": 37.9,
      "turnoverPercentage": 10.1,
      "offensiveLineRank": 4.8,
      "runningBackSoS": 25,
      "passRank": 19,
      "rushRank": 8,
      "imageUrl": "http://content.sportslogos.net/logos/7/165/thumbs/406.gif"
    },
    {
      "rank": 24,
      "team": "Denver Broncos",
      "abbreviation": "DEN",
      "bye": 10,
      "pointsFor": 329,
      "yards": 5602,
      "plays": 1015,
      "yardsPerPlay": 5.5,
      "turnovers": 21,
      "completions": 367,
      "attempts": 588,
      "passYardsTeam": 3695,
      "passTdTeam": 19,
      "interception": 15,
      "netYardsPerAttempt": 5.9,
      "rushAttemptTeam": 393,
      "rushYardsTeam": 1907,
      "rushTdTeam": 18,
      "yardsPerRush": 4.9,
      "scorePercentage": 30.6,
      "turnoverPercentage": 11.3,
      "offensiveLineRank": 13.8,
      "runningBackSoS": 11,
      "passRank": 25,
      "rushRank": 11,
      "imageUrl": "http://content.sportslogos.net/logos/7/161/thumbs/9ebzja2zfeigaziee8y605aqp.gif"
    },
    {
      "rank": 25,
      "team": "Detroit Lions",
      "abbreviation": "DET",
      "bye": 5,
      "pointsFor": 324,
      "yards": 5236,
      "plays": 1019,
      "yardsPerPlay": 5.1,
      "turnovers": 19,
      "completions": 375,
      "attempts": 574,
      "passYardsTeam": 3576,
      "passTdTeam": 22,
      "interception": 12,
      "netYardsPerAttempt": 5.8,
      "rushAttemptTeam": 404,
      "rushYardsTeam": 1660,
      "rushTdTeam": 11,
      "yardsPerRush": 4.1,
      "scorePercentage": 35.3,
      "turnoverPercentage": 11,
      "offensiveLineRank": 19,
      "runningBackSoS": 12,
      "passRank": 17,
      "rushRank": 23,
      "imageUrl": "http://content.sportslogos.net/logos/7/170/thumbs/17013982017.gif"
    },
    {
      "rank": 1000,
      "team": "Free Agent",
      "abbreviation": "FA",
      "bye": 0,
      "pointsFor": 0,
      "yards": 0,
      "plays": 0,
      "yardsPerPlay": 0,
      "turnovers": 0,
      "completions": 0,
      "attempts": 0,
      "passYardsTeam": 0,
      "passTdTeam": 0,
      "interception": 0,
      "netYardsPerAttempt": 0,
      "rushAttemptTeam": 0,
      "rushYardsTeam": 0,
      "rushTdTeam": 0,
      "yardsPerRush": 0,
      "scorePercentage": 0,
      "turnoverPercentage": 0,
      "offensiveLineRank": 100,
      "runningBackSoS": 100,
      "passRank": 100,
      "rushRank": 100,
      "imageUrl": "http://content.sportslogos.net/logos/7/1007/thumbs/dwuw5lojnwsj12vfe0hfa6z47.gif"
    },
    {
      "rank": 15,
      "team": "Green Bay Packers",
      "abbreviation": "GB",
      "bye": 11,
      "pointsFor": 376,
      "yards": 5905,
      "plays": 1026,
      "yardsPerPlay": 5.8,
      "turnovers": 15,
      "completions": 392,
      "attempts": 640,
      "passYardsTeam": 4238,
      "passTdTeam": 25,
      "interception": 4,
      "netYardsPerAttempt": 6.1,
      "rushAttemptTeam": 333,
      "rushYardsTeam": 1667,
      "rushTdTeam": 14,
      "yardsPerRush": 5,
      "scorePercentage": 38.8,
      "turnoverPercentage": 6.7,
      "offensiveLineRank": 7.8,
      "runningBackSoS": 28,
      "passRank": 16,
      "rushRank": 2,
      "imageUrl": "http://content.sportslogos.net/logos/7/171/thumbs/dcy03myfhffbki5d7il3.gif"
    },
    {
      "rank": 11,
      "team": "Houston Texans",
      "abbreviation": "HOU",
      "bye": 10,
      "pointsFor": 402,
      "yards": 5802,
      "plays": 1040,
      "yardsPerPlay": 5.6,
      "turnovers": 16,
      "completions": 345,
      "attempts": 506,
      "passYardsTeam": 3781,
      "passTdTeam": 26,
      "interception": 9,
      "netYardsPerAttempt": 6.7,
      "rushAttemptTeam": 472,
      "rushYardsTeam": 2021,
      "rushTdTeam": 12,
      "yardsPerRush": 4.3,
      "scorePercentage": 40.3,
      "turnoverPercentage": 8.1,
      "offensiveLineRank": 30,
      "runningBackSoS": 29,
      "passRank": 12,
      "rushRank": 18,
      "imageUrl": "http://content.sportslogos.net/logos/7/157/thumbs/570.gif"
    },
    {
      "rank": 5,
      "team": "Indianapolis Colts",
      "abbreviation": "IND",
      "bye": 6,
      "pointsFor": 433,
      "yards": 6179,
      "plays": 1070,
      "yardsPerPlay": 5.8,
      "turnovers": 24,
      "completions": 432,
      "attempts": 644,
      "passYardsTeam": 4461,
      "passTdTeam": 39,
      "interception": 15,
      "netYardsPerAttempt": 6.7,
      "rushAttemptTeam": 408,
      "rushYardsTeam": 1718,
      "rushTdTeam": 13,
      "yardsPerRush": 4.2,
      "scorePercentage": 41.2,
      "turnoverPercentage": 13.2,
      "offensiveLineRank": 2.8,
      "runningBackSoS": 27,
      "passRank": 9,
      "rushRank": 21,
      "imageUrl": "http://content.sportslogos.net/logos/7/158/thumbs/593.gif"
    },
    {
      "rank": 31,
      "team": "Jacksonville Jaguars",
      "abbreviation": "JAC",
      "bye": 10,
      "pointsFor": 245,
      "yards": 4832,
      "plays": 1005,
      "yardsPerPlay": 4.8,
      "turnovers": 29,
      "completions": 329,
      "attempts": 536,
      "passYardsTeam": 3109,
      "passTdTeam": 15,
      "interception": 13,
      "netYardsPerAttempt": 5.3,
      "rushAttemptTeam": 416,
      "rushYardsTeam": 1723,
      "rushTdTeam": 7,
      "yardsPerRush": 4.1,
      "scorePercentage": 25,
      "turnoverPercentage": 15.6,
      "offensiveLineRank": 19,
      "runningBackSoS": 18,
      "passRank": 30,
      "rushRank": 25,
      "imageUrl": "http://content.sportslogos.net/logos/7/159/thumbs/15988562013.gif"
    },
    {
      "rank": 1,
      "team": "Kansas City Chiefs",
      "abbreviation": "KC",
      "bye": 12,
      "pointsFor": 565,
      "yards": 6810,
      "plays": 996,
      "yardsPerPlay": 6.8,
      "turnovers": 18,
      "completions": 385,
      "attempts": 583,
      "passYardsTeam": 4955,
      "passTdTeam": 50,
      "interception": 12,
      "netYardsPerAttempt": 8.1,
      "rushAttemptTeam": 387,
      "rushYardsTeam": 1855,
      "rushTdTeam": 16,
      "yardsPerRush": 4.8,
      "scorePercentage": 52.6,
      "turnoverPercentage": 10.5,
      "offensiveLineRank": 15.5,
      "runningBackSoS": 31,
      "passRank": 1,
      "rushRank": 4,
      "imageUrl": "http://content.sportslogos.net/logos/7/162/thumbs/857.gif"
    },
    {
      "rank": 8,
      "team": "Los Angeles Chargers",
      "abbreviation": "LAC",
      "bye": 12,
      "pointsFor": 428,
      "yards": 5962,
      "plays": 945,
      "yardsPerPlay": 6.3,
      "turnovers": 19,
      "completions": 348,
      "attempts": 512,
      "passYardsTeam": 4089,
      "passTdTeam": 32,
      "interception": 12,
      "netYardsPerAttempt": 7.5,
      "rushAttemptTeam": 399,
      "rushYardsTeam": 1873,
      "rushTdTeam": 16,
      "yardsPerRush": 4.7,
      "scorePercentage": 42.4,
      "turnoverPercentage": 10,
      "offensiveLineRank": 19,
      "runningBackSoS": 26,
      "passRank": 6,
      "rushRank": 10,
      "imageUrl": "http://content.sportslogos.net/logos/7/6446/thumbs/644624152017.gif"
    },
    {
      "rank": 2,
      "team": "Los Angeles Rams",
      "abbreviation": "LAR",
      "bye": 9,
      "pointsFor": 527,
      "yards": 6738,
      "plays": 1060,
      "yardsPerPlay": 6.4,
      "turnovers": 19,
      "completions": 368,
      "attempts": 568,
      "passYardsTeam": 4507,
      "passTdTeam": 32,
      "interception": 12,
      "netYardsPerAttempt": 7.5,
      "rushAttemptTeam": 459,
      "rushYardsTeam": 2231,
      "rushTdTeam": 23,
      "yardsPerRush": 4.9,
      "scorePercentage": 48.6,
      "turnoverPercentage": 9.8,
      "offensiveLineRank": 11.3,
      "runningBackSoS": 21,
      "passRank": 5,
      "rushRank": 1,
      "imageUrl": "http://content.sportslogos.net/logos/7/5941/thumbs/594179532017.gif"
    },
    {
      "rank": 26,
      "team": "Miami Dolphins",
      "abbreviation": "MIA",
      "bye": 5,
      "pointsFor": 319,
      "yards": 4638,
      "plays": 878,
      "yardsPerPlay": 5.3,
      "turnovers": 23,
      "completions": 292,
      "attempts": 455,
      "passYardsTeam": 2900,
      "passTdTeam": 26,
      "interception": 13,
      "netYardsPerAttempt": 5.7,
      "rushAttemptTeam": 371,
      "rushYardsTeam": 1738,
      "rushTdTeam": 7,
      "yardsPerRush": 4.7,
      "scorePercentage": 28.3,
      "turnoverPercentage": 12.5,
      "offensiveLineRank": 31,
      "runningBackSoS": 13,
      "passRank": 27,
      "rushRank": 22,
      "imageUrl": "http://content.sportslogos.net/logos/7/150/thumbs/15073062018.gif"
    },
    {
      "rank": 19,
      "team": "Minnesota Vikings",
      "abbreviation": "MIN",
      "bye": 12,
      "pointsFor": 360,
      "yards": 5529,
      "plays": 1003,
      "yardsPerPlay": 5.5,
      "turnovers": 20,
      "completions": 425,
      "attempts": 606,
      "passYardsTeam": 4036,
      "passTdTeam": 30,
      "interception": 10,
      "netYardsPerAttempt": 6.2,
      "rushAttemptTeam": 357,
      "rushYardsTeam": 1493,
      "rushTdTeam": 9,
      "yardsPerRush": 4.2,
      "scorePercentage": 32.4,
      "turnoverPercentage": 10.6,
      "offensiveLineRank": 23.3,
      "runningBackSoS": 5,
      "passRank": 22,
      "rushRank": 29,
      "imageUrl": "http://content.sportslogos.net/logos/7/172/thumbs/17227042013.gif"
    },
    {
      "rank": 4,
      "team": "New England Patriots",
      "abbreviation": "NE",
      "bye": 10,
      "pointsFor": 436,
      "yards": 6295,
      "plays": 1073,
      "yardsPerPlay": 5.9,
      "turnovers": 18,
      "completions": 378,
      "attempts": 574,
      "passYardsTeam": 4258,
      "passTdTeam": 29,
      "interception": 11,
      "netYardsPerAttempt": 7.2,
      "rushAttemptTeam": 478,
      "rushYardsTeam": 2037,
      "rushTdTeam": 18,
      "yardsPerRush": 4.3,
      "scorePercentage": 40.8,
      "turnoverPercentage": 9.2,
      "offensiveLineRank": 4,
      "runningBackSoS": 4,
      "passRank": 3,
      "rushRank": 9,
      "imageUrl": "http://content.sportslogos.net/logos/7/151/thumbs/y71myf8mlwlk8lbgagh3fd5e0.gif"
    },
    {
      "rank": 3,
      "team": "New Orleans Saints",
      "abbreviation": "NO",
      "bye": 9,
      "pointsFor": 504,
      "yards": 6067,
      "plays": 1010,
      "yardsPerPlay": 6,
      "turnovers": 16,
      "completions": 381,
      "attempts": 519,
      "passYardsTeam": 4042,
      "passTdTeam": 33,
      "interception": 7,
      "netYardsPerAttempt": 7.5,
      "rushAttemptTeam": 471,
      "rushYardsTeam": 2025,
      "rushTdTeam": 26,
      "yardsPerRush": 4.3,
      "scorePercentage": 51.8,
      "turnoverPercentage": 9.5,
      "offensiveLineRank": 4,
      "runningBackSoS": 24,
      "passRank": 2,
      "rushRank": 6,
      "imageUrl": "http://content.sportslogos.net/logos/7/175/thumbs/907.gif"
    },
    {
      "rank": 16,
      "team": "New York Giants",
      "abbreviation": "NYG",
      "bye": 11,
      "pointsFor": 369,
      "yards": 5697,
      "plays": 984,
      "yardsPerPlay": 5.8,
      "turnovers": 19,
      "completions": 382,
      "attempts": 583,
      "passYardsTeam": 4047,
      "passTdTeam": 23,
      "interception": 12,
      "netYardsPerAttempt": 6.4,
      "rushAttemptTeam": 354,
      "rushYardsTeam": 1650,
      "rushTdTeam": 13,
      "yardsPerRush": 4.7,
      "scorePercentage": 38.4,
      "turnoverPercentage": 9.6,
      "offensiveLineRank": 16.5,
      "runningBackSoS": 17,
      "passRank": 15,
      "rushRank": 14,
      "imageUrl": "http://content.sportslogos.net/logos/7/166/thumbs/919.gif"
    },
    {
      "rank": 23,
      "team": "New York Jets",
      "abbreviation": "NYJ",
      "bye": 4,
      "pointsFor": 333,
      "yards": 4787,
      "plays": 971,
      "yardsPerPlay": 4.9,
      "turnovers": 30,
      "completions": 299,
      "attempts": 524,
      "passYardsTeam": 3165,
      "passTdTeam": 18,
      "interception": 19,
      "netYardsPerAttempt": 5.6,
      "rushAttemptTeam": 410,
      "rushYardsTeam": 1622,
      "rushTdTeam": 11,
      "yardsPerRush": 4,
      "scorePercentage": 32,
      "turnoverPercentage": 14.7,
      "offensiveLineRank": 28,
      "runningBackSoS": 7,
      "passRank": 29,
      "rushRank": 32,
      "imageUrl": "http://content.sportslogos.net/logos/7/152/thumbs/15291162019.gif"
    },
    {
      "rank": 28,
      "team": "Oakland Raiders",
      "abbreviation": "OAK",
      "bye": 6,
      "pointsFor": 290,
      "yards": 5379,
      "plays": 995,
      "yardsPerPlay": 5.4,
      "turnovers": 24,
      "completions": 382,
      "attempts": 556,
      "passYardsTeam": 3751,
      "passTdTeam": 19,
      "interception": 10,
      "netYardsPerAttempt": 6.2,
      "rushAttemptTeam": 387,
      "rushYardsTeam": 1628,
      "rushTdTeam": 9,
      "yardsPerRush": 4.2,
      "scorePercentage": 31.3,
      "turnoverPercentage": 13.6,
      "offensiveLineRank": 24.8,
      "runningBackSoS": 14,
      "passRank": 24,
      "rushRank": 31,
      "imageUrl": "http://content.sportslogos.net/logos/7/163/thumbs/g9mgk6x3ge26t44cccm9oq1vl.gif"
    },
    {
      "rank": 18,
      "team": "Philadelphia Eagles",
      "abbreviation": "PHI",
      "bye": 10,
      "pointsFor": 367,
      "yards": 5845,
      "plays": 1037,
      "yardsPerPlay": 5.6,
      "turnovers": 23,
      "completions": 422,
      "attempts": 599,
      "passYardsTeam": 4275,
      "passTdTeam": 29,
      "interception": 11,
      "netYardsPerAttempt": 6.7,
      "rushAttemptTeam": 398,
      "rushYardsTeam": 1570,
      "rushTdTeam": 12,
      "yardsPerRush": 3.9,
      "scorePercentage": 38.1,
      "turnoverPercentage": 12.5,
      "offensiveLineRank": 5.3,
      "runningBackSoS": 23,
      "passRank": 10,
      "rushRank": 27,
      "imageUrl": "http://content.sportslogos.net/logos/7/167/thumbs/960.gif"
    },
    {
      "rank": 6,
      "team": "Pittsburgh Steelers",
      "abbreviation": "PIT",
      "bye": 7,
      "pointsFor": 428,
      "yards": 6453,
      "plays": 1058,
      "yardsPerPlay": 6.1,
      "turnovers": 26,
      "completions": 459,
      "attempts": 689,
      "passYardsTeam": 5008,
      "passTdTeam": 35,
      "interception": 17,
      "netYardsPerAttempt": 7,
      "rushAttemptTeam": 345,
      "rushYardsTeam": 1445,
      "rushTdTeam": 16,
      "yardsPerRush": 4.2,
      "scorePercentage": 36.8,
      "turnoverPercentage": 14.3,
      "offensiveLineRank": 4.3,
      "runningBackSoS": 2,
      "passRank": 7,
      "rushRank": 17,
      "imageUrl": "http://content.sportslogos.net/logos/7/156/thumbs/970.gif"
    },
    {
      "rank": 7,
      "team": "Seattle Seahawks",
      "abbreviation": "SEA",
      "bye": 11,
      "pointsFor": 428,
      "yards": 5653,
      "plays": 1012,
      "yardsPerPlay": 5.6,
      "turnovers": 11,
      "completions": 280,
      "attempts": 427,
      "passYardsTeam": 3093,
      "passTdTeam": 35,
      "interception": 7,
      "netYardsPerAttempt": 6.5,
      "rushAttemptTeam": 534,
      "rushYardsTeam": 2560,
      "rushTdTeam": 15,
      "yardsPerRush": 4.8,
      "scorePercentage": 39.8,
      "turnoverPercentage": 6.1,
      "offensiveLineRank": 21.8,
      "runningBackSoS": 6,
      "passRank": 11,
      "rushRank": 7,
      "imageUrl": "http://content.sportslogos.net/logos/7/180/thumbs/pfiobtreaq7j0pzvadktsc6jv.gif"
    },
    {
      "rank": 21,
      "team": "San Francisco 49ers",
      "abbreviation": "SF",
      "bye": 4,
      "pointsFor": 342,
      "yards": 5769,
      "plays": 1003,
      "yardsPerPlay": 5.8,
      "turnovers": 32,
      "completions": 331,
      "attempts": 532,
      "passYardsTeam": 3867,
      "passTdTeam": 26,
      "interception": 20,
      "netYardsPerAttempt": 6.7,
      "rushAttemptTeam": 423,
      "rushYardsTeam": 1902,
      "rushTdTeam": 7,
      "yardsPerRush": 4.5,
      "scorePercentage": 37,
      "turnoverPercentage": 17.1,
      "offensiveLineRank": 16.5,
      "runningBackSoS": 3,
      "passRank": 21,
      "rushRank": 26,
      "imageUrl": "http://content.sportslogos.net/logos/7/179/thumbs/17994552009.gif"
    },
    {
      "rank": 12,
      "team": "Tampa Bay Buccaneers",
      "abbreviation": "TB",
      "bye": 7,
      "pointsFor": 396,
      "yards": 6648,
      "plays": 1055,
      "yardsPerPlay": 6.3,
      "turnovers": 35,
      "completions": 408,
      "attempts": 625,
      "passYardsTeam": 5125,
      "passTdTeam": 36,
      "interception": 26,
      "netYardsPerAttempt": 7.7,
      "rushAttemptTeam": 389,
      "rushYardsTeam": 1523,
      "rushTdTeam": 11,
      "yardsPerRush": 3.9,
      "scorePercentage": 37,
      "turnoverPercentage": 19,
      "offensiveLineRank": 28,
      "runningBackSoS": 30,
      "passRank": 8,
      "rushRank": 28,
      "imageUrl": "http://content.sportslogos.net/logos/7/176/thumbs/17636702014.gif"
    },
    {
      "rank": 27,
      "team": "Tennessee Titans",
      "abbreviation": "TEN",
      "bye": 11,
      "pointsFor": 310,
      "yards": 5002,
      "plays": 940,
      "yardsPerPlay": 5.3,
      "turnovers": 18,
      "completions": 293,
      "attempts": 437,
      "passYardsTeam": 2975,
      "passTdTeam": 16,
      "interception": 12,
      "netYardsPerAttempt": 6.1,
      "rushAttemptTeam": 456,
      "rushYardsTeam": 2027,
      "rushTdTeam": 15,
      "yardsPerRush": 4.4,
      "scorePercentage": 34.9,
      "turnoverPercentage": 10.2,
      "offensiveLineRank": 14.5,
      "runningBackSoS": 15,
      "passRank": 26,
      "rushRank": 13,
      "imageUrl": "http://content.sportslogos.net/logos/7/160/thumbs/1053.gif"
    },
    {
      "rank": 29,
      "team": "Washington Redskins",
      "abbreviation": "WAS",
      "bye": 10,
      "pointsFor": 281,
      "yards": 4795,
      "plays": 967,
      "yardsPerPlay": 5,
      "turnovers": 19,
      "completions": 311,
      "attempts": 509,
      "passYardsTeam": 3021,
      "passTdTeam": 16,
      "interception": 15,
      "netYardsPerAttempt": 5.5,
      "rushAttemptTeam": 414,
      "rushYardsTeam": 1774,
      "rushTdTeam": 12,
      "yardsPerRush": 4.3,
      "scorePercentage": 31.8,
      "turnoverPercentage": 11.2,
      "offensiveLineRank": 20.5,
      "runningBackSoS": 22,
      "passRank": 28,
      "rushRank": 15,
      "imageUrl": "http://content.sportslogos.net/logos/7/168/thumbs/im5xz2q9bjbg44xep08bf5czq.gif"
    }
  ];